services:

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512M


  tests:
    build:
      context: ./
      dockerfile: ./src/services/unittests/
    command: python -m unittest discover -s tests
    container_name: tests
    environment:
      - ENVIRON=${ENVIRON}
    privileged: true
    develop:
      watch:
        - action: sync
          path: ./src/tests
          target: ./app/tests
        - action: sync
          path: ./src/parts
          target: ./app/tests/parts
        - action: sync
          path: ./src/client
          target: ./app/tests/client
    depends_on:
      - mqtt-broker


  listener:
    build: ./src/services/listener
    command: python main.py
    container_name: listener
    environment:
      - ENVIRON=${ENVIRON}
    develop:
      watch:
        - action: sync+restart
          path: ./src/services/listener/main.py
          target: ./app/main.py
    depends_on:
      - mqtt-broker


  vehicle:
    build:
      context: ./
      dockerfile: ./src/services/vehicle
    container_name: vehicle
    tty: true
    privileged: true
    environment:
      - ENVIRON=${ENVIRON}
    develop:
      watch:
        - action: sync
          path: src/services/vehicle
          target: app/
        - action: sync
          path: src/parts
          target: app/parts
        - action: sync
          path: src/client
          target: app/client
    depends_on:
      - mqtt-broker


  ultrasonic:
    build:
      context: ./
      dockerfile: ./src/services/ultrasonic/Dockerfile
    container_name: ultrasonic
    working_dir: /app
    tty: true
    privileged: true
    environment:
      - ENVIRON=${ENVIRON}
    develop:
      watch:
        - action: sync
          path: ./src/services/ultrasonic
          target: app/
        - action: sync
          path: src/parts
          target: app/parts
        - action: sync
          path: src/client
          target: app/client
    depends_on:
      - mqtt-broker


  infrared:
    build:
      context: ./
      dockerfile: ./src/services/infrared/Dockerfile
    container_name: infrared
    working_dir: /app
    tty: true
    privileged: true
    environment:
      - ENVIRON=${ENVIRON}
    develop:
      watch:
        - action: sync
          path: ./src/services/infrared
          target: app/
        - action: sync
          path: src/parts
          target: app/parts
        - action: sync
          path: src/client
          target: app/client
    depends_on:
      - mqtt-broker

  camera:
    build:
      context: ./
      dockerfile: ./src/services/camera/Dockerfile
    container_name: camera
    tty: true
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - DISPLAY=:0
    develop:
      watch:
        - action: sync+restart
          path: ./src/parts/camera.py
          target: app/camera.py
    depends_on:
      - mqtt-broker
